plugins {
    id 'java'
    id 'net.neoforged.moddev'
}

base {
    archivesName = "${mod_name}-xplat"
}
version = "${mc_version}-${build_number}"
if (System.getenv().RELEASE_MODE == null) {
    version += '-SNAPSHOT'
}

neoForge {
    // To find the timestamp, see https://projects.neoforged.net/neoforged/neoform
    // Updated to a version for Minecraft 1.21.5
    neoFormVersion = "1.21.5-20250325.162830"
    addModdingDependenciesTo sourceSets.test
}

repositories {
    maven {
        name = "JEI"
        url "https://maven.blamejared.com/"
        content {
            includeGroup "mezz.jei"
        }
    }
}

dependencies {
    compileOnly group: 'org.spongepowered', name: 'mixin', version: '0.8.5'
    // Aligned JEI version with the NeoForge subproject for consistency
    compileOnly "mezz.jei:jei-1.21.5-common-api:21.4.0.27"
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.6.1'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.6.1'
}

test {
    useJUnitPlatform()
}

processResources {
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            groupId project.group
            artifactId project.archivesBaseName
            version project.version
            from components.java
        }
    }
    repositories {
        maven {
            url "file://" + System.getenv("local_maven")
        }
    }
}