plugins {
    id 'java'
    id 'net.neoforged.moddev'
}

neoForge {
    // To find the timestamp, see https://projects.neoforged.net/neoforged/neoform
    neoFormVersion = neoform_version
    addModdingDependenciesTo sourceSets.test
}

dependencies {
    compileOnly 'org.spongepowered:mixin:0.8.5'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.6.1'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}
