buildscript {
    repositories {
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath "com.diffplug.spotless:spotless-plugin-gradle:6.23.3"
    }
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'pmd'
    apply plugin: "com.diffplug.spotless"
    apply plugin: 'maven-publish'
    java.toolchain.languageVersion = JavaLanguageVersion.of(java_version)
    java.withSourcesJar()
    base.archivesName = "${mod_name}-${it.name}".toLowerCase()

    version = "${mc_version}-${build_number}"
    if (System.getenv().RELEASE_MODE != "1") {
        version += '-SNAPSHOT'
    }

    repositories {
        mavenLocal()
        mavenCentral()
        maven {
            name = "JEI"
            url "https://maven.blamejared.com/"
            content {
                includeGroup "mezz.jei"
            }
        }
    }

    dependencies {
        compileOnly "mezz.jei:jei-${jei_mc_version}-common-api:${jei_version}"
    }

    if (it.name != 'Xplat') {
        def xplat = project(":Xplat")

        dependencies {
            implementation xplat
        }

        gradle.projectsEvaluated {
            compileJava {
                source xplat.sourceSets.main.allSource
            }

            processResources {
                from xplat.sourceSets.main.resources
            }
    
            sourcesJar {
                from xplat.sourceSets.main.allJava
            }
        }
    }

    tasks.withType(JavaCompile).configureEach {
        it.options.encoding = 'UTF-8'
        it.options.release = java.toolchain.languageVersion.map { it.asInt() }
    }

    tasks.withType(GenerateModuleMetadata).configureEach {
        it.enabled = false
    }

    pmd {
        toolVersion '6.35.0'
        incrementalAnalysis.set(true)
        ruleSetFiles = rootProject.files("spotless/pmd-ruleset.xml")
    }

    jar {
        from "LICENSE"

        exclude "**/*.bat"
        exclude "**/*.psd"
        exclude "**/*.exe"
        exclude "**/unused"

        // exclude test data
        exclude "**/assets/patchouli/patchouli_books/**"
        exclude "**/data/patchouli/patchouli_books/**"
        exclude "**/data/patchouli/advancements/**"
        exclude "**/data/patchouli/recipes/**"
    }

    spotless {
        enforceCheck = false // workaround around jenkins having wrong line endings in some files
        // we explicitly check in github actions builds
        java {
            indentWithTabs()
            eclipse().configFile rootProject.file('spotless/eclipseformat.xml')
            removeUnusedImports()
            importOrderFile rootProject.file('spotless/eclipse.importorder')
        }
    }

    publishing {
        publications {
            mavenJava(MavenPublication) {
                groupId project.group
                artifactId project.base.archivesName.get()
                version project.version
                from components.java
            }
        }
        repositories {
            maven {
                url System.getenv("local_maven")
            }
        }
    }
}
