buildscript {
    repositories {
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath "com.diffplug.spotless:spotless-plugin-gradle:6.23.3"
    }
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'pmd'
    apply plugin: "com.diffplug.spotless"
    apply plugin: 'maven-publish'
    java.toolchain.languageVersion = JavaLanguageVersion.of(java_version)
    java.withSourcesJar()
    base.archivesName = "${mod_name}-${it.name}".toLowerCase()

    it.version = "${mc_version}-${build_number}"
    if (System.getenv().RELEASE_MODE != "1") {
        it.version += '-SNAPSHOT'
    }

    it.repositories {
        mavenLocal()
        mavenCentral()
        maven {
            name = "JEI"
            url "https://maven.blamejared.com/"
            content {
                includeGroup "mezz.jei"
            }
        }
    }

    it.dependencies {
        compileOnly "mezz.jei:jei-${jei_mc_version}-common-api:${jei_version}"
    }

    if (it.name != 'Xplat') {
        def xplat = project(":Xplat")

        it.dependencies {
            implementation xplat
        }

        def properties = [
            "version": project.version,
            "mod_name": mod_name,
            "mod_id": mod_id,
            "mod_description": mod_description,
            "mc_min_version": mc_min_version,
            "mc_max_version": mc_max_version,
            "neoforge_version_range": neoforge_version_range,
            "fabric_loader_version": fabric_loader,
            "fabric_api_version": fabric_api,
        ]

        it.processResources {
            inputs.properties properties

            filesMatching(["fabric.mod.json", "META-INF/neoforge.mods.toml"]) {
                expand properties
            }
        }

        gradle.projectsEvaluated {
            compileJava {
                source xplat.sourceSets.main.allSource
            }

            processResources {
                from xplat.sourceSets.main.resources
            }

            processTestResources {
                from xplat.sourceSets.test.resources
            }

            sourcesJar {
                from xplat.sourceSets.main.allJava
            }
        }
    }

    it.tasks.withType(JavaCompile).configureEach {
        it.options.encoding = 'UTF-8'
        it.options.release = java.toolchain.languageVersion.map { it.asInt() }
    }

    it.tasks.withType(GenerateModuleMetadata).configureEach {
        it.enabled = false
    }

    it.pmd {
        toolVersion '6.35.0'
        incrementalAnalysis.set(true)
        ruleSetFiles = rootProject.files("spotless/pmd-ruleset.xml")
    }

    it.jar {
        from "LICENSE"

        exclude "**/*.bat"
        exclude "**/*.psd"
        exclude "**/*.exe"
        exclude "**/unused"
    }

    it.spotless {
        enforceCheck = false // workaround around jenkins having wrong line endings in some files
        // we explicitly check in github actions builds
        java {
            indentWithTabs()
            eclipse().configFile rootProject.file('spotless/eclipseformat.xml')
            removeUnusedImports()
            importOrderFile rootProject.file('spotless/eclipse.importorder')
        }
    }

    it.publishing {
        publications {
            mavenJava(MavenPublication) {
                groupId project.group
                artifactId project.base.archivesName.get()
                version project.version
                from components.java
            }
        }
        repositories {
            maven {
                url System.getenv("local_maven")
            }
        }
    }
}
