# Done to increase the memory available to gradle.
# add-exports are needed for spotless to work on new Javas
org.gradle.jvmargs=-Xmx1G \
  --add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED

mc_version=26.1
build_number=94
group=vazkii.patchouli
mod_name=Patchouli

loom_version=1.15-SNAPSHOT
fabric_loader=0.18.4
fabric_api=0.144.0+26.1
fiber_version=0.23.0-2

jei_version=29.1.0.16
jei_mc_version=26.1-pre-3

#rei_version=21.9.812
#cloth_config_version=21.11.153

mdg_version=2.0.141
neoform_version=26.1-1
neoforge_version=26.1.0.1-beta
