pluginManagement {
    plugins {
        id 'net.neoforged.moddev' version mdg_version apply false
        id 'net.fabricmc.fabric-loom' version loom_version apply false
    }
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            name = 'NeoForge'
            url = 'https://maven.neoforged.net/releases'
        }
        gradlePluginPortal()
    }
}

plugins {
    // Required for NeoGradle
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.8.0'
}

rootProject.name = 'Patchouli'
include("Xplat", "Fabric", "NeoForge")
