modLoader="javafml"
license="CC BY-NC-SA 3.0"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/VazkiiMods/Patchouli"
logoFile="logo.png"

[[mods]]
modId="${mod_id}"
displayName="${mod_name}"
version="${version}"
authors="Vazkii, williewillus"
description='''
${mod_description}
'''

[[dependencies.patchouli]]
modId="neoforge"
type="REQUIRED"
versionRange="${neoforge_version_range}"

[[dependencies.patchouli]]
modId="minecraft"
type="REQUIRED"
versionRange="[${mc_min_version},${mc_max_version})"

[[mixins]]
config="patchouli_xplat.mixins.json"
